name: mudder_dart

version: 0.2.0-nullsafety.0

description: >-
  Dart port of mudderjs (https://github.com/fasiha/mudderjs).

homepage: https://github.com/tiagocpeixoto/mudder-dart

documentation: https://github.com/tiagocpeixoto/mudder-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: '>=1.16.5 <2.0.0'
  effective_dart: ^1.3.1
